### ISSUE TITLE
Trouble getting USB to boot

### ISSUE THREAD

**Issue by RDRRdev** [gordonb3/bubba-overlay#3]
Hi there!

This is almost certainly an issue on my side and apologies for taking your time with it, but I'm hoping you might have some tips to help me narrow down the problem.

I have a B3 (with disk, no wifi). I bought it thinking I would eventually use it and never really did (beyond initial setup and playing around). 

Now, I have a need for something like it and found your awesome system. But I can't get it to load. Without a USB and following your listed process, my B3 works as expected and I can access the web UI (though I don't remember the password). With a USB, I get to the purple light and never any further. 

I've tried a few different USB drives (including a SanDisk Cruzer Fit CZ33 8GB USB Flash which seemed to be closest to some of the devices in the working list of disks). I've tried with and without WAN. 

Any thoughts on what I might try to troubleshoot or how I could get extra info about what's going on?

Thank you for the work to keep these out of date devices useful!

**Comment by RDRRdev** [comment]
My version says b3 on the back but it doesn't have the debossed B3 on the front.

**Comment by gordonb3** [comment]
What LED sequence are you seeing with the USB? The correct sequence should be: green - purple - off - purple - green

Also what version of the live USB are you trying to run?

**Comment by RDRRdev** [comment]
Thank you for your time! And apologies - I've realised I put this in the wrong location (bubba-overlay).

Lights -
* With usb drive plugged in and holding power upon cold boot for 5 seconds (both tried with and without wan):
Green (~39 sec), nothing (~6 sec), then purple indefinitely (have let it run for hours). 

* With usb drive plugged in, booting normally to blue light, holding power button to power down, then pressing and holding power button to start booting from usb (with wan):
Green (~39 sec), nothing (~6 sec), then purple indefinitely. 

* Without holding the power button upon boot:
Purple (~50 seconds) then blue indefinitely. 


Version-
bubbagenb3img-1.15.0 

Based on those symptoms, does it sound like a USB drive compatibility issue? I've tried 3 at this stage, but I could just be unlucky. 

There is also a good chance I'm doing something wrong. In your instructions are there any "so obvious everyone should know" steps - because I might be missing them. I'm using a Rasberry Pi to follow your exact instructions on creating the image.

**Comment by gordonb3** [comment]
No worries about the wrong location.

Seems that somehow I misconfigured my test environment which is why I had the LED sequence wrong. The sequence you describe is the correct one however it appears I managed to mix up some equally named files between the various boot setups.

The problem with the image you downloaded is that it passes incorrect parameters to the kernel which does not stop my test machine from booting because my hard drive contains bubbagen as well but in your case it can't mount the root partition and panics.

The fix is fairly easy. What you need to do is mount the first partition on the USB thumb drive and edit the file `boot.ini`
- enable both `ROOT` and `ROOTDELAY` (remove the hashtag)
- change the value for ROOT to read `"PARTUUID=05A8FC63-03"`

See attached file [boot.txt](https://github.com/gordonb3/bubba-overlay/files/11090439/boot.txt)

**Comment by RDRRdev** [comment]
It worked - yay, thank you!!

**Comment by gordonb3** [comment]
Excellent. I updated the images with the correct boot.ini

Closing issue.
